[project]
name = "persist-query"
version = "0.0.0"
edition = "2018"

[dependencies]
hyper = "0.13"
hyper-tls = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.9"
url = "2.1"
