[project]
name = "relay-compiler"
version = "0.0.0"
edition = "2018"

[dependencies]
graphql-syntax = { path = "../graphql-syntax" }
extract-graphql = { path = "../extract-graphql" }
common = { path = "../common" }
interner = { path = "../interner" }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.45"
thiserror = "1.0.9"
watchman_client = "0.5.0"
rayon = "1.3.0"
